// -- Schlumberger Private --

#undef ENUMKEYWORD
#undef ENUMNAMESPACE

#ifdef MANAGED
#define ENUMKEYWORD public enum class
//#define ENUMNAMESPACE GPM_EnumShareManaged
#else
#define ENUMKEYWORD enum
//#define ENUMNAMESPACE GPM_EnumShare
#endif
// Need to use this for inclusion in c++ and c++/cli


// For map files
 ENUMKEYWORD PARM_GRID_MAP_NAMES {
     TOP=0,
	 SV_X_OBSOLETE,
	 SV_Y_OBSOLETE,
	 PVX,
	 PVY,
	 PVZ,
	 POR,
	 PRS,
	 DEPODEPTH,
	 EROSION,
	 SRC,
	 TEC,
	 TOP_SLOPE_X,
	 TOP_SLOPE_Y,
     WATER_TOP_FLUID,
	 WATER_TOP_FLUID_VEL_X,
	 WATER_TOP_FLUID_VEL_Y,
	 WATER_TOP_TURB,
	 WATER_TOP_TURB_VEL_X,
	 WATER_TOP_TURB_VEL_Y,
	 LITHOLOGY,
	 WAVE_ENERGY_DISSIP,
	 WAVE_TRAVEL_TIME,
	 WAVE_DIR_X,
	 WAVE_DIR_Y,
	 WAVE_VEL_EFF_X,
	 WAVE_VEL_EFF_Y,
	 WAVE_LONGSHORE_DIR_X,
	 WAVE_LONGSHORE_DIR_Y,
	 WAVE_LONGSHORE_VEL_X,
	 WAVE_LONGSHORE_VEL_Y,
	 SED_MOVE_X,
	 SED_MOVE_Y,
	 SEALEVEL,
	 REL_SEALEVEL_CHANGE_RATE,
     RES_TIME_DEF,
     WAVE_INDUCED_ZONE_FLOW,
     WAVE_INDUCED_ZONE_SURFACE,
     RESIDENCE_LATTORAL,
     PERMEABILITY_HORI,
     PERMEABILITY_VERT,
	 OGS_PRESSURE,
     OGS_VELOCITY_X,
     OGS_VELOCITY_Y,
     OGS_VELOCITY_Z,
     CARBONATE_DROWNING_HEIGHT,
	 DIFFUSION_ENERGY, 
 	 STEADY_FLOW_ENERGY, 
 	 UNSTEADY_FLOW_ENERGY, 
 	 WAVE_DISSIPATION_ENERGY,
 	 WAVE_ONSHORE_ENERGY, 
 	 WAVE_LONGSHORE_ENERGY, 
 	 WATER_BOTTOM_VELOCITY,
     WAVE_HORIZONTAL_DIFFUSION_ENERGY,
	 NPARM_GRID_MAP_NAMES};

 ENUMKEYWORD PARM_GRID_VECTOR_2D_NAMES{
	 SV=0,
	 TOP_SLOPE,
	 WATER_TOP_FLUID_VEL,
	 WATER_TOP_TURB_VEL,
	 WAVE_DIR,
	 WAVE_LONGSHORE_VEL,
	 WAVE_LONGSHORE_DIR,
	 WAVE_VEL_EFF,
	 SED_MOVE
 };

// For map files
 ENUMKEYWORD PARM_GRID_MAP_1_INDEX_NAMES {
	 SED_j,
	 INSITU_GROWTH_j,
	 RES_TIME_j,
     DIAGENESIS_j,
     DEPOSITION_CONTRIBUTION_j,
     RES_TIME_SURF_j,
     ERODABILITY_j,
	 NPARM_GRID_MAP_1_INDEX_NAMES};


 ENUMKEYWORD PARM_DEPOSITIONAL_ENERGY_PROCESS_NAMES{
     DIFFUSION_PROCESS,
     STEADY_FLOW_PROCESS,
     UNSTEADY_FLOW_PROCESS,
     CARBONATE_PROCESS,
     WAVE_PROCESS_ENERGY_DISSIPATION,
     WAVE_PROCESS_ONSHORE,
     WAVE_PROCESS_LONGSHORE,
     NUM_PARM_DEPOSITIONAL_ENERGY_PROCESS_NAMES
 };

//}    

