// -- Schlumberger Private --

#undef ENUMKEYWORD
#undef ENUMNAMESPACE

#ifdef MANAGED
#define ENUMKEYWORD public enum class
#define ENUMCLASSKEYWORD public enum class
//#define ENUMNAMESPACE GPM_EnumShareManaged
#else
#define ENUMKEYWORD enum
#define ENUMCLASSKEYWORD enum class
//#define ENUMNAMESPACE GPM_EnumShare
#endif
//namespace ENUMNAMESPACE{
 ENUMKEYWORD  PARC_MEMBERS {
    MAPFILE = 0,
    FLOWFILE,
    SEDFILE,
    CARBFILE,
    OUTFILE,
    SEDFLAG,
    SEAFLAG,
    FLOWFLAG,
    ARROWS,
    PARROWS,
    PORFLG,
    PRSFLG,
    COMPFLAG,
    CARBFLAG,
    PERMUN,
    CMPUN,
    TIMBEG,
    TIMEND,
    TIMRUN,
    TDISPLAY,
    ALTHICK,
    BASEROD,
    DTIME,
    ISAVE,
	SAVE_LAST_TIMESTEP_ONLY,
    DEPODEPTHFLAG,
    EROSIONFLAG,     // Put out erosion surface for timestep
    SEACURVEEXTREMAFLAG, // Use extrema of sea curve as time displays; 
    POSTPROCESSFLAG, // Shall we do postprocessing and what type
    POSTPROCESSFILE, // Name of the outputfile
    POSTPROCESSPARMS, // The file with the input parms
    PARC_VERSION,
	AREA_SEDIMENT_PARMS,
	DO_AREA_SEDIMENT,
	DIFFUSION_PARMS,
	DO_DIFFUSION,
	STEADY_FLOW_PARMS,
	DO_STEADY_FLOW,
	UNSTEADY_FLOW_PARMS,
	DO_UNSTEADY_FLOW,
	WAVE_PARMS,
	DO_WAVES,
	LITHO_CLASSIFICATION_PARMS,
	DO_LITHO_CLASSIFICATION,
	COMPACTION_PARMS,
	DO_COMPACTION,
	TECTONICS_PARMS,
	DO_TECTONICS,
	MODEL_SAMPLING_PARMS,
	DO_MODEL_SAMPLING,
	POINT_SEDIMENT_PARMS,
	DO_POINT_SEDIMENT,
	DIAGENESIS_PARMS,
	DO_DIAGENESIS,
    RUN_OPTIMIZED_CODE,
	DO_LOG_PROCESS_ENERGY,
	ISOSTATIC_TECTONICS_PARMS,
	DO_ISOSTATIC_TECTONICS,
    FLOW_SIMULATOR_OUTPUT_PARMS,
    DO_FLOW_SIMULATOR_OUTPUT,
    PELAGIC_RAIN_PARMS,
    DO_PELAGIC_RAIN,
    PLUGINS_CTRL_PARMS,
    DO_PLUGINS,
	DO_BATHYMETRY,
    DO_SAVE_LAST_TIMESTEP_ONLY,
    DO_OUTPUT_INCREMENTAL_FILES,
	DO_INCLUDE_ACTIVE_LAYER,
    NPARC};
    
    ENUMCLASSKEYWORD ARROWS_OPTIONS{ ARROWS_OFF=0, ARROWS_SLOP};
    ENUMKEYWORD PARROWS_OPTIONS{ PARROWS_OFF=0, PARROWS_VEL, PARROWS_FLOW};
 
    ENUMKEYWORD COMPFLAG_OPTIONS{ COMPFLAG_OFF=0, COMPFLAG_LOAD, COMPFLAG_LOAD_AND_WATER_FLOW, COMPFLAG_LOAD_AND_WATER_FLOW_3D};
    ENUMKEYWORD SEACURVEEXTEMAFLAG_OPTIONS{ SEACURVEEXTEMAFLAG_OFF=0, SEACURVEEXTEMAFLAG_ONLY, SEACURVEEXTEMAFLAG_AND_DISPLAYTIME};
    ENUMKEYWORD POSTPROCESSINGFLAG_OPTIONS{ POSTPROCESSINGFLAG_OFF = 0, POSTPROCESSINGFLAG_REDUCTION = 1, POSTPROCESSINGFLAG_TRANSFORM=2};
//    }
